### ISSUE TITLE
fix landscape/background

### ISSUE THREAD

**Issue by GuapoTaco** [fuzzything44/RPG-Simulator#11]
OK. There are some serious problems with your system.

1. Jerky rendering (shouldn't be too hard to fix)
2. Too many copies of images. You should do a key-value style because currently you have one copy of each texture for each square on your background, which leads to WAY more memory usage. I have ~171mb which isn't too much, but we could optimize it a lot more (prly half).

This line allocates a LOT of memory, and mostly copies:

backgroundImages = new Image[(int) (chunkRes.X) * chunks.length][(int) (chunkRes.Y) * chunks[0].length];

One good solution is just a texture library thing that could be loaded from a file, and maybe a string or int key to that image. Of course that would have to go in the world loading too.

**Comment by fuzzything44** [comment]
Okay, since they aren't copies this could be closed for now.
Except! When we render them, we rescale the image for every single image being drawn. I could implement hashmap to see if it is scaled, but only if it becomes a performance issue.

**Comment by GuapoTaco** [comment]
Well, one thing to do about optimization is not to see if it is needed, but
to just do it if it is as low hanging fruit as this one. Just something to
keep in mind.
