### ISSUE TITLE
Visual studio licenses

### ISSUE THREAD

**Issue by GuapoTaco** [fuzzything44/RPG-Simulator#14]
Alright, we need to make a plan as far as visual studio goes. Here are our many options:

1. Stick with express. Problems: we don't get sweet sweet NSIGHT debugging. Just look up NSIGHT debugging OpenGL and you`ll see what I mean. I mean, shader debugging, buffer viewing, the whole works just to name a few. So an option but it would seriously slow development. 

2. Buy visual studio professional. Ouch. I think it's about 800 dollars. We could do a Kickstarter before we start selling though.....

3. BizSpark. A Microsoft thing that would let us get it for free until it runs out (three years) Or start making 1m per year.  We would need to convince Microsoft that we are serious, so like a website and company name and a game name.

NSIGHT is free for commercial use, so that wouldn't be a problem, you just need to be a part of the nvida developer program, which I already am. It's free and easy to get accepted.

**Comment by GuapoTaco** [comment]
Ere is a new thing called visual studio community, which gives small businesses an extensible express version, which is perfect.

Closing issue.

[here is a link to the page](http://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx)

**Comment by fuzzything44** [comment]
Yea, that's what I got.
