### ISSUE TITLE
Do we want this to be a privite repo?

### ISSUE THREAD

**Issue by GuapoTaco** [fuzzything44/RPG-Simulator#9]
You can easily get 5 free private repos for being a student. If we ever want this to be a sold game, then we should do this. 

https://education.github.com/pack

There are a bunch of other tools there too if you are interested (including UE4!)

**Comment by fuzzything44** [comment]
Well, I submitted a form to get the package. So now we ca wait and see if it is accepted.

**Comment by GuapoTaco** [comment]
Did u say that ur poor and stuff bc dats what I did and they accepted it In
a heartbeat.

**Comment by fuzzything44** [comment]
It should be private now.
